name: Sync to Nextcloud

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync to Nextcloud via WebDAV
        uses: dav-action/upload-webdav@v1
        with:
          server: https://02c4bf9ee095.ngrok-free.app
          username: ${{ secrets.NEXTCLOUD_USERNAME }}
          password: ${{ secrets.NEXTCLOUD_PASSWORD }}
          source: ./
          destination: /remote.php/dav/files/${{ secrets.NEXTCLOUD_USERNAME }}/Project-Code-Live/
          exclude: .git*,.github*
