name: Sync to Nextcloud

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync to Nextcloud via WebDAV
        uses: puppe/webdav-sync@v2.2.0
        with:
          remote_url: https://02c4bf9ee095.ngrok-free.app/remote.php/dav/files/${{ secrets.NEXTCLOUD_USERNAME }}/Project-Code-Live/
          local_path: ./
          webdav_username: ${{ secrets.NEXTCLOUD_USERNAME }}
          webdav_password: ${{ secrets.NEXTCLOUD_PASSWORD }}
          exclude: ".git*,.github*"
