name: Sync to Nextcloud (Manual WebDAV)

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create a test file for this demo
        run: echo "This file was auto-deployed by a GitHub Action at $(date)" > LIVE_DEMO.txt

      - name: Upload file to Nextcloud via WebDAV
        run: |
          curl -u "${{ secrets.NEXTCLOUD_USERNAME }}:${{ secrets.NEXTCLOUD_PASSWORD }}" \
          -T "LIVE_DEMO.txt" \
          "https://02c4bf9ee095.ngrok-free.app/remote.php/dav/files/${{ secrets.NEXTCLOUD_USERNAME }}/Project-Code-Live/LIVE_DEMO.txt"
